### ISSUE TITLE
building base image error 

### ISSUE THREAD

**Issue by Charlotte-Gao** [soulteary/docker-midjourney-prompt-generator#8]
hey, l'm trying to build the base image, but got this error 
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 11: FROM requires either one or three arguments
could you help with it pls? 
Cheers
Charlotte

**Comment by soulteary** [comment]
Hello, it seems that the issue here is caused by a lower version of Docker. 

Lower versions of Docker may not be able to recognize the keywords in the building process correctly.

You can consider upgrading the Docker version. Please refer to #7 for more information.

https://github.com/soulteary/docker-prompt-generator/issues/7 @Charlotte-Gao
